---
apiVersion: v1
kind: Secret
metadata:
  name: kendyala-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rosa916-rvhvd/kendyala-gateway-gitops
